[package]
name = "sf-plugin-template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", default-features = false, features = ["dynamic_linking"] }
bevy_reflect = { version = "0.14.2", features = ["bevy"] }
dyn-clone = "1.0"
strategyforge-core = { path = "../StrategyForge-Core" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = []

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
